create table private.builtin_scenario_secrets (
  scenario_id text primary key,
  instructor_notes text not null,
  client_responses jsonb not null,
  constraint builtin_scenario_secrets_responses_check
    check (client_responses = '{}'::jsonb or private.valid_client_responses(1, client_responses))
);

alter table private.builtin_scenario_secrets enable row level security;
revoke all on table private.builtin_scenario_secrets from public, anon, authenticated;

insert into private.builtin_scenario_secrets (scenario_id, instructor_notes, client_responses) values
  ('sc-net-f26-01', 'SETUP: Pod at documented baseline; label devices R1/R2/S1/S2 and provide two known-good laptops. No configuration changes required.
ROTATION: Cohort discovery, then teams of three rotate lead/communication, physical identification, and evidence roles. Every student must physically trace and identify at least one connection.
DIAGNOSTIC BRANCHES: A missing label is resolved by tracing; damaged power/network hardware is an escalation, not a repair.
VERIFY: Student identifies every device, console path, endpoint path, power isolation point, and safety equipment.
RESET: Return cables to labeled storage positions; power state matches baseline; chairs and floor paths clear.
PRINTED SERVICE LOG: Pod diagram, device/port identifiers, one safety observation, one escalation boundary, instructor initials.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Only the equipment named in this ticket is affected.","quality":"exact"},"timing_change":{"response":"The issue was noticed during today''s setup; no other change is confirmed.","quality":"exact"},"symptom_error":{"response":"There is no additional error message beyond the symptom in the ticket.","quality":"exact"},"environment_equipment":{"response":"Use the assigned Cisco pod and the two designated lab laptops.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was attempted before the ticket was opened.","quality":"exact"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-02', 'SETUP: One known-good reference cable; materials for two student cables; assign equivalent tester-fault cards (open, reversal, split pair).
ROTATION: Each student must terminate or reterminate at least one end and personally run/interpret one tester cycle.
DIAGNOSTIC BRANCHES: Visual order error, incomplete seating, excessive untwist, or tester-indicated fault.
VERIFY: Wire map passes end-to-end and both students explain the observed failed result before correction.
RESET: Scrap ends disposed; tools counted; tester leads and known-good cable returned separately.
PRINTED SERVICE LOG: Standard used, tool/action/why/observed rows, initial and final tester results, cable identifier, instructor initials.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Only the equipment named in this ticket is affected.","quality":"exact"},"timing_change":{"response":"The issue was noticed during today''s setup; no other change is confirmed.","quality":"exact"},"symptom_error":{"response":"One tester result may show an open, reversal, or split pair; the exact result depends on your assigned variant.","quality":"exact"},"environment_equipment":{"response":"Use the assigned bulk cable, connectors, crimper, visual aids, and cable tester.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was attempted before the ticket was opened.","quality":"exact"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-03', 'SETUP: Two laptops and switch; stage one equivalent fault: bad/loose cable, disabled adapter, wrong switch port, or incorrect endpoint address.
DIAGNOSTIC BRANCHES: No link -> physical; link/no neighbor -> interface/address; local works/remote fails -> network path. Do not reveal the layer.
VERIFY: Student states failed layer, discriminating test, correction, and ping/link proof.
RESET: Restore baseline cable, adapter state, port, and addressing; verify both endpoints.
PRINTED SERVICE LOG: Initial symptom, layered hypotheses, five evidence rows, final proof, and client-facing explanation.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Only one of the two assigned laptops is reported affected.","quality":"exact"},"timing_change":{"response":"The user remembers moving cables earlier, but is not sure which one.","quality":"ambiguous"},"symptom_error":{"response":"There is no additional error message beyond the symptom in the ticket.","quality":"exact"},"environment_equipment":{"response":"Use the assigned Cisco pod and the two designated lab laptops.","quality":"exact"},"prior_troubleshooting":{"response":"The user unplugged and reconnected one cable without labeling it.","quality":"exact"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-04', 'SETUP: Same-LAN switch path and address cards with equivalent /24 or /26 endpoint pairs; one card per pair.
ROTATION: Each student configures one endpoint, then cross-verifies the partner''s work.
DIAGNOSTIC BRANCHES: Duplicate address, mask mismatch, wrong gateway field, or disabled interface variant.
VERIFY: Record effective settings and bidirectional ping; explain which fields matter for same-subnet traffic.
RESET: Return endpoints to DHCP/baseline and confirm no static values remain.
PRINTED SERVICE LOG: Address card, before/after configuration, duplicate check, bidirectional proof, individual role.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Only the two replacement laptops are in scope; do not alter Cisco device configuration.","quality":"exact"},"timing_change":{"response":"The issue was noticed during today''s setup; no other change is confirmed.","quality":"exact"},"symptom_error":{"response":"There is no additional error message beyond the symptom in the ticket.","quality":"exact"},"environment_equipment":{"response":"Use the two assigned laptops and the access switch shown on the station card.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was attempted before the ticket was opened.","quality":"exact"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-05', 'SETUP: Equivalent cards drawn from /26, /27, and /28 networks with equal calculation load; include one invalid proposed address. Preparation rotation uses paper before any equipment.
DIAGNOSTIC BRANCHES: Wrong boundary, invalid reserved address, insufficient hosts, or mismatched prefix.
VERIFY: Student explains boundary increment, usable range, and why the flagged address fails. Optional endpoint proof after calculation.
RESET: Erase temporary device values; return subnet cards by variant.
PRINTED SERVICE LOG: Binary or boundary work, network/broadcast/host range, rejected address with reason, verification method.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Validate only the subnet card assigned to you.","quality":"exact"},"timing_change":{"response":"The issue was noticed during today''s setup; no other change is confirmed.","quality":"exact"},"symptom_error":{"response":"At least one proposed address may be the network address, broadcast address, or outside the assigned subnet.","quality":"exact"},"environment_equipment":{"response":"Use the assigned Cisco pod and the two designated lab laptops.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was attempted before the ticket was opened.","quality":"exact"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-06', 'SETUP: One switch per active team, console path, two laptops, known-good patch leads, pod-specific hostname/credential card. Baseline contains no student config.
ROTATIONS: Team A configures while Team B calculates/annotates port and verification plan; swap. Every student must make a console change or cable/verify a port.
DIAGNOSTIC BRANCHES: Wrong console port/settings, administratively down port, bad cable, or mistaken password report. No VLAN work.
VERIFY: show running-config identity, interface status, learned MACs, and endpoint ping.
RESET: erase startup-config/reload or execute approved baseline script; verify baseline prompt and inventory cables.
PRINTED SERVICE LOG: Commands with purpose (no passwords), port/MAC evidence, ping proof, personal console/cabling contribution.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Only the equipment named in this ticket is affected.","quality":"exact"},"timing_change":{"response":"The issue was noticed during today''s setup; no other change is confirmed.","quality":"exact"},"symptom_error":{"response":"There is no additional error message beyond the symptom in the ticket.","quality":"exact"},"environment_equipment":{"response":"Use the assigned Cisco switch, console cable, two laptops, and sealed lab credential card.","quality":"exact"},"prior_troubleshooting":{"response":"Someone tried a password from another pod and assumed the switch was broken.","quality":"mistaken"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-07', 'SETUP: One router, console cable, laptop, patch cable, and equivalent /27 or /28 interface card. Use one LAN interface only.
ROTATION: Each student performs part of console configuration and independently verifies addressing/cabling.
DIAGNOSTIC BRANCHES: Administratively down, wrong mask, wrong laptop gateway, wrong physical interface, or cable fault.
VERIFY: show ip interface brief, running interface stanza, laptop effective config, and gateway ping. No static route commands.
RESET: remove interface address/description, shutdown to baseline, restore laptop DHCP, inventory cables.
PRINTED SERVICE LOG: Address calculation, command purpose, before/after interface state, gateway proof, individual contribution.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Only the equipment named in this ticket is affected.","quality":"exact"},"timing_change":{"response":"A technician says the router was reset recently, but cannot confirm what configuration remained.","quality":"ambiguous"},"symptom_error":{"response":"The laptop reports that its configured gateway is unreachable.","quality":"exact"},"environment_equipment":{"response":"Use the assigned Cisco pod and the two designated lab laptops.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was attempted before the ticket was opened.","quality":"exact"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-08', 'SETUP: Controlled wireless/AP station or simulation plus three client cards: invalid/missing DHCP lease, incorrect DNS, and healthy wireless reference. Do not require production AP changes.
ROTATION: Lead handles client questions; hands-on role inspects client config; evidence role runs address/name tests. Every student must inspect, cable, or run a client test and record it. Rotate next week.
DIAGNOSTIC BRANCHES: DHCP failure vs DNS failure vs weak/interfered radio path. User actions are not proof.
VERIFY: Lease/effective settings, IP ping, name lookup, and signal observation identify separate fault domains.
RESET: Forget lab SSID if required, restore automatic addressing/DNS, return AP and clients to baseline.
PRINTED SERVICE LOG: Per-client symptom matrix, ordered tests, evidence-to-layer conclusion, escalation/recommendation.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Three assigned clients are in scope; the wired pod baseline should not be reconfigured.","quality":"exact"},"timing_change":{"response":"A user says this started after ''the Wi-Fi box was moved,'' but the timing is uncertain.","quality":"ambiguous"},"symptom_error":{"response":"One client lacks a valid lease; a second reaches the test IP but not the test hostname.","quality":"exact"},"environment_equipment":{"response":"Use the assigned Cisco pod and the two designated lab laptops.","quality":"exact"},"prior_troubleshooting":{"response":"A user rebooted the access point twice and moved a laptop closer.","quality":"exact"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-09', 'SETUP: Stage one equivalent fault per pod: wrong endpoint mask, shutdown router interface, wrong switch port/cable, or duplicate endpoint address. Preserve a sealed baseline/variant card.
ROTATIONS: Two teams of three per pod. Rotation A performs console/cabling while B calculates subnet and plans verification; swap using equivalent fault.
DIAGNOSTIC BRANCHES: Students must collect state before change and localize physical, switching, router-interface, or endpoint configuration.
VERIFY: Cable/link proof, show output, effective endpoint settings, gateway ping, peer ping where topology permits, and stated root cause.
RESET: Execute pod baseline checklist; erase staged changes; independently verify by instructor card.
PRINTED SERVICE LOG: Initial state, hypothesis branches, five discriminating tests, final proof, reset confirmation, individual console/cabling role.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"One switch, one router LAN interface, and two laptops are in scope.","quality":"exact"},"timing_change":{"response":"The prior team says they changed ''an address and maybe a cable,'' but did not record which.","quality":"ambiguous"},"symptom_error":{"response":"At least one endpoint cannot reach the assigned gateway.","quality":"exact"},"environment_equipment":{"response":"Use the assigned Cisco pod and the two designated lab laptops.","quality":"exact"},"prior_troubleshooting":{"response":"They copied commands from another pod and then power-cycled both devices.","quality":"mistaken"},"impact_urgency":{"response":"This blocks the assigned lab station, but no production service is affected.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-final-a', 'SETUP: Variant A; subnet 10.44.18.0/27; sealed fault: router interface administratively down. Prepare one router, two switches, laptops, console leads, tested patch leads, and clean baseline configs.
ROTATIONS: Teams of three. Rotation A configures/cables while Rotation B completes subnet/ticket analysis; swap with an equivalent variant. Roles: lead/client, hands-on, evidence/documentation. Every student must console or cable and record it.
DIAGNOSTIC BRANCHES: Physical wire-map/link, switch forwarding/MAC learning, router interface status/address, endpoint address/mask/gateway. No VLAN or static-route configuration.
VERIFY: Subnet work, pod/laptop cabling, switch identity, router interface config, effective endpoint settings, gateway/peer connectivity, relevant show output, root-cause proof.
RESET: Instructor observes saved evidence, then team restores approved pod baseline, automatic laptop settings, cable inventory, and clean work area.
PRINTED SERVICE LOG: One individual log per student linked to child ticket; assigned role; personal console/cabling action; five evidence rows; shared outcome reference; connectivity proof; reset and instructor initials.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Use one router LAN interface, both switches as assigned by the pod card, and the designated laptops.","quality":"exact"},"timing_change":{"response":"The pod was returned from another training rotation; its exact last change is not documented.","quality":"ambiguous"},"symptom_error":{"response":"One assigned laptop cannot reach its configured gateway; no more specific error was reported.","quality":"exact"},"environment_equipment":{"response":"Use pod 1, the assigned console leads, tested patch cables, laptops, and approved subnet card.","quality":"exact"},"prior_troubleshooting":{"response":"The previous group says they rebooted equipment and tried an address from a neighboring pod.","quality":"mistaken"},"impact_urgency":{"response":"The pod must pass instructor acceptance before the next rotation can begin.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-final-b', 'SETUP: Variant B; subnet 10.44.22.64/27; sealed fault: one endpoint uses the broadcast address. Prepare one router, two switches, laptops, console leads, tested patch leads, and clean baseline configs.
ROTATIONS: Teams of three. Rotation A configures/cables while Rotation B completes subnet/ticket analysis; swap with an equivalent variant. Roles: lead/client, hands-on, evidence/documentation. Every student must console or cable and record it.
DIAGNOSTIC BRANCHES: Physical wire-map/link, switch forwarding/MAC learning, router interface status/address, endpoint address/mask/gateway. No VLAN or static-route configuration.
VERIFY: Subnet work, pod/laptop cabling, switch identity, router interface config, effective endpoint settings, gateway/peer connectivity, relevant show output, root-cause proof.
RESET: Instructor observes saved evidence, then team restores approved pod baseline, automatic laptop settings, cable inventory, and clean work area.
PRINTED SERVICE LOG: One individual log per student linked to child ticket; assigned role; personal console/cabling action; five evidence rows; shared outcome reference; connectivity proof; reset and instructor initials.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Use one router LAN interface, both switches as assigned by the pod card, and the designated laptops.","quality":"exact"},"timing_change":{"response":"The pod was returned from another training rotation; its exact last change is not documented.","quality":"ambiguous"},"symptom_error":{"response":"One assigned laptop cannot reach its configured gateway; no more specific error was reported.","quality":"exact"},"environment_equipment":{"response":"Use pod 2, the assigned console leads, tested patch cables, laptops, and approved subnet card.","quality":"exact"},"prior_troubleshooting":{"response":"The previous group says they rebooted equipment and tried an address from a neighboring pod.","quality":"mistaken"},"impact_urgency":{"response":"The pod must pass instructor acceptance before the next rotation can begin.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-final-c', 'SETUP: Variant C; subnet 172.20.48.0/28; sealed fault: one patch lead fails wire-map testing. Prepare one router, two switches, laptops, console leads, tested patch leads, and clean baseline configs.
ROTATIONS: Teams of three. Rotation A configures/cables while Rotation B completes subnet/ticket analysis; swap with an equivalent variant. Roles: lead/client, hands-on, evidence/documentation. Every student must console or cable and record it.
DIAGNOSTIC BRANCHES: Physical wire-map/link, switch forwarding/MAC learning, router interface status/address, endpoint address/mask/gateway. No VLAN or static-route configuration.
VERIFY: Subnet work, pod/laptop cabling, switch identity, router interface config, effective endpoint settings, gateway/peer connectivity, relevant show output, root-cause proof.
RESET: Instructor observes saved evidence, then team restores approved pod baseline, automatic laptop settings, cable inventory, and clean work area.
PRINTED SERVICE LOG: One individual log per student linked to child ticket; assigned role; personal console/cabling action; five evidence rows; shared outcome reference; connectivity proof; reset and instructor initials.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Use one router LAN interface, both switches as assigned by the pod card, and the designated laptops.","quality":"exact"},"timing_change":{"response":"The pod was returned from another training rotation; its exact last change is not documented.","quality":"ambiguous"},"symptom_error":{"response":"One assigned laptop cannot reach its configured gateway; no more specific error was reported.","quality":"exact"},"environment_equipment":{"response":"Use pod 3, the assigned console leads, tested patch cables, laptops, and approved subnet card.","quality":"exact"},"prior_troubleshooting":{"response":"The previous group says they rebooted equipment and tried an address from a neighboring pod.","quality":"mistaken"},"impact_urgency":{"response":"The pod must pass instructor acceptance before the next rotation can begin.","quality":"exact"}}'::jsonb),
  ('sc-net-f26-final-d', 'SETUP: Variant D; subnet 192.168.72.128/28; sealed fault: one endpoint has the wrong subnet mask. Prepare one router, two switches, laptops, console leads, tested patch leads, and clean baseline configs.
ROTATIONS: Teams of three. Rotation A configures/cables while Rotation B completes subnet/ticket analysis; swap with an equivalent variant. Roles: lead/client, hands-on, evidence/documentation. Every student must console or cable and record it.
DIAGNOSTIC BRANCHES: Physical wire-map/link, switch forwarding/MAC learning, router interface status/address, endpoint address/mask/gateway. No VLAN or static-route configuration.
VERIFY: Subnet work, pod/laptop cabling, switch identity, router interface config, effective endpoint settings, gateway/peer connectivity, relevant show output, root-cause proof.
RESET: Instructor observes saved evidence, then team restores approved pod baseline, automatic laptop settings, cable inventory, and clean work area.
PRINTED SERVICE LOG: One individual log per student linked to child ticket; assigned role; personal console/cabling action; five evidence rows; shared outcome reference; connectivity proof; reset and instructor initials.
SCOPE BOUNDARY: VLAN and static-route configuration are not assessed or authorized.', '{"scope":{"response":"Use one router LAN interface, both switches as assigned by the pod card, and the designated laptops.","quality":"exact"},"timing_change":{"response":"The pod was returned from another training rotation; its exact last change is not documented.","quality":"ambiguous"},"symptom_error":{"response":"One assigned laptop cannot reach its configured gateway; no more specific error was reported.","quality":"exact"},"environment_equipment":{"response":"Use pod 4, the assigned console leads, tested patch cables, laptops, and approved subnet card.","quality":"exact"},"prior_troubleshooting":{"response":"The previous group says they rebooted equipment and tried an address from a neighboring pod.","quality":"mistaken"},"impact_urgency":{"response":"The pod must pass instructor acceptance before the next rotation can begin.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-05', 'PREPARATION: Review power-path diagram, connector identification, ESD, discharge wait, and stop-work conditions.
EQUIPMENT: One proven bench system per pair, outlet/power strip, known-good cord, PSU tester, known-good PSU, flashlight, ESD mat. Multimeter use only at instructor-approved external test points.
SETUP: Stage one equivalent safe fault: switched-off strip/PSU, loose AC lead, disconnected 24-pin ATX, disconnected CPU power, or front-panel start lead on wrong pins. System is de-energized before staging.
ROLES: One student leads communication and records the power path; the other performs hands-on tests. Both must inspect/connect and verify; rotate next lab.
DIAGNOSTIC BRANCHES: No AC input; AC present/no standby; standby present/no start signal; start/no POST. Require a discriminating observation before substitution.
VERIFY: Correct connector/state, safe startup, stable fans, and successful POST/firmware entry.
RESET: Shut down, disconnect AC, discharge, restore sealed baseline card, inventory known-good items, and independently recheck start.
SIGN-OFF: Safe handling, stated power-path evidence, POST proof, and baseline reset.
PRINTED SERVICE LOG: Initial symptom, safety step, power-path hypotheses, tool/action/why/observed rows, root cause, POST proof, personal contribution, instructor initials.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"Only the assigned open-bench computer and listed accessories are in scope.","quality":"exact"},"timing_change":{"response":"I moved the bench and wiped around the cables shortly before it stopped starting.","quality":"exact"},"symptom_error":{"response":"There is no fan movement, indicator, or POST response.","quality":"exact"},"environment_equipment":{"response":"Use the assigned ESD mat, parts set, known-good comparison parts, and approved test tools.","quality":"exact"},"prior_troubleshooting":{"response":"I pressed the power control several times and pushed on a few connectors without labeling them.","quality":"ambiguous"},"impact_urgency":{"response":"The assigned training station is unavailable, but no production system is affected.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-06', 'PREPARATION: Manufacturer lookup for board memory slots and POST indicators; review ESD and de-energized reseating.
EQUIPMENT: Proven bench system, speaker/diagnostic LEDs if available, compatible RAM, one labeled known-good module, display, ESD mat.
SETUP: Stage one safe variant: partially seated module, module in nonpreferred single-DIMM slot, incompatible/mismatched pair, contaminated contact simulation card (do not damage contacts), or display path masking a successful POST.
ROLES: Each student performs one de-energized memory configuration and independently interprets one POST observation.
DIAGNOSTIC BRANCHES: No POST indication; memory-specific indication; successful POST/no display; intermittent restart. Research exact board documentation before concluding.
VERIFY: Repeatable POST, firmware reports expected memory amount/channel, and two cold starts succeed.
RESET: Power off/discharge, reinstall baseline RAM in documented slots, remove staged item, record kit inventory, cold-start check.
SIGN-OFF: Safe reseating, evidence-to-diagnosis reasoning, memory detection, and reset.
PRINTED SERVICE LOG: Manufacturer source/search, POST evidence, slot diagram, discriminating tests, final firmware memory result, personal contribution.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"Motherboard, installed memory, display path, and POST indicators are in scope; storage and operating system are not.","quality":"exact"},"timing_change":{"response":"The symptom was noticed at the start of today''s check; no confirmed change is documented.","quality":"exact"},"symptom_error":{"response":"It powers on, but the display stays blank. I heard a pattern once but did not count it carefully.","quality":"ambiguous"},"environment_equipment":{"response":"Use the assigned ESD mat, parts set, known-good comparison parts, and approved test tools.","quality":"exact"},"prior_troubleshooting":{"response":"I removed and reinstalled memory without checking the motherboard slot guidance.","quality":"exact"},"impact_urgency":{"response":"The assigned training station is unavailable, but no production system is affected.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-07', 'PREPARATION: Identify SATA data/power and available motherboard storage interfaces; research assigned board/device compatibility.
EQUIPMENT: Proven bench system, assigned SSD, known-good SATA data lead, known-good power branch, spare compatible SSD, ESD mat.
SETUP: Stage one equivalent fault: missing data lead, missing power, failed/loose data lead, disabled/incorrect firmware port setting where safely supported, or incompatible-device card requiring escalation rather than installation.
ROLES: Individual ticket. Instructor may pair students only for observation; each student performs and records their own installation/test.
DIAGNOSTIC BRANCHES: No power/physical detection; cable/port path; device substitution; compatibility/firmware boundary. No OS, driver, formatting, or data-recovery work.
VERIFY: Device identified by correct model/capacity in firmware through two cold starts; compatibility source recorded.
RESET: De-energize, restore baseline device/cables/firmware setting, return known-good items separately, confirm baseline detection.
SIGN-OFF: Correct connectors, firmware proof, compatibility reasoning, and reset.
PRINTED SERVICE LOG: Asset/model, manufacturer source, before/after firmware evidence, cable/port/device tests, conclusion or escalation, instructor initials.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"Only the assigned open-bench computer and listed accessories are in scope.","quality":"exact"},"timing_change":{"response":"The symptom began immediately after the storage device was installed.","quality":"exact"},"symptom_error":{"response":"The device is absent from the firmware storage list.","quality":"exact"},"environment_equipment":{"response":"Use the assigned ESD mat, parts set, known-good comparison parts, and approved test tools.","quality":"exact"},"prior_troubleshooting":{"response":"Someone moved both the data and power cables, but did not test either cable separately.","quality":"ambiguous"},"impact_urgency":{"response":"The assigned training station is unavailable, but no production system is affected.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-08', 'PREPARATION: Review display paths, onboard versus discrete outputs, port types, safe cleaning, and fan restraint.
EQUIPMENT: Proven bench system, monitor, known-good display cable, keyboard/mouse, USB test device, flashlight, ESD-safe brush, approved compressed air.
SETUP: Stage two independent safe faults: wrong monitor input/loose display cable/inactive onboard output plus bad peripheral/loose USB path. Add visible dust only where it can be cleaned without opening a PSU.
ROLES: Each student owns one fault branch, then cross-verifies the other''s result and participates in reset.
DIAGNOSTIC BRANCHES: Confirm POST first; display power/input/cable/output/GPU; peripheral/device/port; maintenance observation. Do not collapse all symptoms into one diagnosis.
VERIFY: Stable firmware display, repeated keyboard/mouse/USB response, fans unobstructed, and two restarts.
RESET: De-energize, restore baseline cable/input/port, remove staged peripheral, clean work area, count accessories, verify baseline.
SIGN-OFF: Safe cleaning, independent fault evidence, stable final state, and reset.
PRINTED SERVICE LOG: Separate hypothesis/evidence chain for each fault, maintenance action and reason, known-good substitutions, final verification, personal role.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"Display, video connection, keyboard/mouse, external ports, cooling path, and visible dust are in scope.","quality":"exact"},"timing_change":{"response":"The desk was rearranged recently, but I cannot say whether the problem began before or after that.","quality":"ambiguous"},"symptom_error":{"response":"The display reports no signal; one USB peripheral intermittently loses power.","quality":"exact"},"environment_equipment":{"response":"Use the assigned ESD mat, parts set, known-good comparison parts, and approved test tools.","quality":"exact"},"prior_troubleshooting":{"response":"I moved the display cable to another connector and used compressed air very close to a fan.","quality":"mistaken"},"impact_urgency":{"response":"The assigned training station is unavailable, but no production system is affected.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-09', 'PREPARATION: Students receive a model/serial card and must plan manufacturer searches before hands-on work.
EQUIPMENT: Proven bench system, labeled known-good PSU/RAM/display/storage leads, POST reference, flashlight, ESD mat.
SETUP: Stage one ambiguous but safe variant: CPU power loose, RAM marginally seated, display on inactive output, SATA data loose, or front-panel lead shifted. Client history intentionally mentions multiple symptoms but one current root cause.
ROLES: Individual assessment. A peer may act as client or observer but may not touch the system or supply the diagnosis.
DIAGNOSTIC BRANCHES: Preserve current symptom; power checkpoint; POST checkpoint; display; firmware inventory; manufacturer/compatibility; known-good substitution; escalate on damage, unsafe condition, or unresolved evidence.
VERIFY: Three cold starts, stable firmware inventory for CPU/RAM/storage, display/peripheral response, and root cause tied to evidence.
RESET: De-energize, restore baseline, remove all known-good/staged items, reconcile kit checklist, independent instructor cold start.
SIGN-OFF: Communication, triage path, justified conclusion/escalation, stable verification, and reset.
PRINTED SERVICE LOG: Client claim versus observed state, ranked hypotheses, five discriminating tests, manufacturer source/search/result, repeated proof, next-technician handoff.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"Power, board connections, memory, display path, and storage detection are in scope; no operating-system work is authorized.","quality":"exact"},"timing_change":{"response":"Several parts were moved between benches over the last two sessions, but there is no reliable change record.","quality":"ambiguous"},"symptom_error":{"response":"The symptom is inconsistent: no power, no display, or missing storage was reported at different times.","quality":"ambiguous"},"environment_equipment":{"response":"Use the assigned ESD mat, parts set, known-good comparison parts, and approved test tools.","quality":"exact"},"prior_troubleshooting":{"response":"I swapped the board, memory, and power supply together, and it worked once, so I blamed the motherboard.","quality":"mistaken"},"impact_urgency":{"response":"The assigned training station is unavailable, but no production system is affected.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-final-a', 'PREPARATION: Number twelve complete caseless kits; verify compatibility and baseline; seal variant A. Students may use printed books and manufacturer resources.
EQUIPMENT: Motherboard, CPU/cooler, thermal interface material as required, RAM, PSU, storage, display/GPU path, keyboard, ESD mat, approved tools, POST reference, known-good fallback parts.
CAPACITY/ROTATION: Individual final in two waves of up to twelve. Wave B completes compatibility research, ticket analysis, component explanation preparation, and reset-plan review at desks while Wave A builds; then swap. No partner may touch or diagnose another student''s system.
ROLES: Each student is the sole technician for their numbered kit; the instructor is the client, safety authority, checkpoint verifier, and issuer of known-good fallback parts.
SETUP: Student builds from loose parts and reaches instructor checkpoint. With power removed and student away, instructor stages variant A: memory module not fully seated after the initial build checkpoint.
DIAGNOSTIC BRANCHES: Power/no power; POST/memory; successful POST/no display; firmware storage inventory. Student must state why each test discriminates.
VERIFY: Safe complete build, component-function explanation, three cold starts, stable firmware CPU/RAM/storage detection, display/input response, root-cause evidence, readiness for FOG/Linux deployment or known-good laptop fallback.
RESET: De-energize/discharge, disassemble to labeled kit, clean thermal material only as directed, cap/store CPU and board safely, inventory every part/tool, restore staged item, instructor kit sign-off.
SIGN-OFF: Individual build, explanation, diagnosis, manufacturer research, repeated verification, complete reset.
PRINTED SERVICE LOG: One individual log linked to ticket; compatibility evidence; build checkpoints; five diagnostic rows; manufacturer source; final firmware inventory; reset initials.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"The assigned motherboard, CPU/cooler, memory, power supply, storage, display path, and basic input device are in scope.","quality":"exact"},"timing_change":{"response":"The system passed through an instructor checkpoint before the final symptom was observed; the exact change is not documented for the technician.","quality":"ambiguous"},"symptom_error":{"response":"The workstation does not currently reach the expected stable firmware screen with all assigned hardware detected.","quality":"exact"},"environment_equipment":{"response":"Use only the numbered parts kit, ESD mat, approved tools, known-good fallback items issued by the instructor, and bench monitor.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was performed after the symptom appeared.","quality":"exact"},"impact_urgency":{"response":"The workstation must pass hardware acceptance before it can be released to the Networking deployment step.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-final-b', 'PREPARATION: Number twelve complete caseless kits; verify compatibility and baseline; seal variant B. Students may use printed books and manufacturer resources.
EQUIPMENT: Motherboard, CPU/cooler, thermal interface material as required, RAM, PSU, storage, display/GPU path, keyboard, ESD mat, approved tools, POST reference, known-good fallback parts.
CAPACITY/ROTATION: Individual final in two waves of up to twelve. Wave B completes compatibility research, ticket analysis, component explanation preparation, and reset-plan review at desks while Wave A builds; then swap. No partner may touch or diagnose another student''s system.
ROLES: Each student is the sole technician for their numbered kit; the instructor is the client, safety authority, checkpoint verifier, and issuer of known-good fallback parts.
SETUP: Student builds from loose parts and reaches instructor checkpoint. With power removed and student away, instructor stages variant B: CPU auxiliary power disconnected after the initial build checkpoint.
DIAGNOSTIC BRANCHES: Power/no power; POST/memory; successful POST/no display; firmware storage inventory. Student must state why each test discriminates.
VERIFY: Safe complete build, component-function explanation, three cold starts, stable firmware CPU/RAM/storage detection, display/input response, root-cause evidence, readiness for FOG/Linux deployment or known-good laptop fallback.
RESET: De-energize/discharge, disassemble to labeled kit, clean thermal material only as directed, cap/store CPU and board safely, inventory every part/tool, restore staged item, instructor kit sign-off.
SIGN-OFF: Individual build, explanation, diagnosis, manufacturer research, repeated verification, complete reset.
PRINTED SERVICE LOG: One individual log linked to ticket; compatibility evidence; build checkpoints; five diagnostic rows; manufacturer source; final firmware inventory; reset initials.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"The assigned motherboard, CPU/cooler, memory, power supply, storage, display path, and basic input device are in scope.","quality":"exact"},"timing_change":{"response":"The system passed through an instructor checkpoint before the final symptom was observed; the exact change is not documented for the technician.","quality":"ambiguous"},"symptom_error":{"response":"The workstation does not currently reach the expected stable firmware screen with all assigned hardware detected.","quality":"exact"},"environment_equipment":{"response":"Use only the numbered parts kit, ESD mat, approved tools, known-good fallback items issued by the instructor, and bench monitor.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was performed after the symptom appeared.","quality":"exact"},"impact_urgency":{"response":"The workstation must pass hardware acceptance before it can be released to the Networking deployment step.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-final-c', 'PREPARATION: Number twelve complete caseless kits; verify compatibility and baseline; seal variant C. Students may use printed books and manufacturer resources.
EQUIPMENT: Motherboard, CPU/cooler, thermal interface material as required, RAM, PSU, storage, display/GPU path, keyboard, ESD mat, approved tools, POST reference, known-good fallback parts.
CAPACITY/ROTATION: Individual final in two waves of up to twelve. Wave B completes compatibility research, ticket analysis, component explanation preparation, and reset-plan review at desks while Wave A builds; then swap. No partner may touch or diagnose another student''s system.
ROLES: Each student is the sole technician for their numbered kit; the instructor is the client, safety authority, checkpoint verifier, and issuer of known-good fallback parts.
SETUP: Student builds from loose parts and reaches instructor checkpoint. With power removed and student away, instructor stages variant C: display connected to an inactive output after the initial build checkpoint.
DIAGNOSTIC BRANCHES: Power/no power; POST/memory; successful POST/no display; firmware storage inventory. Student must state why each test discriminates.
VERIFY: Safe complete build, component-function explanation, three cold starts, stable firmware CPU/RAM/storage detection, display/input response, root-cause evidence, readiness for FOG/Linux deployment or known-good laptop fallback.
RESET: De-energize/discharge, disassemble to labeled kit, clean thermal material only as directed, cap/store CPU and board safely, inventory every part/tool, restore staged item, instructor kit sign-off.
SIGN-OFF: Individual build, explanation, diagnosis, manufacturer research, repeated verification, complete reset.
PRINTED SERVICE LOG: One individual log linked to ticket; compatibility evidence; build checkpoints; five diagnostic rows; manufacturer source; final firmware inventory; reset initials.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"The assigned motherboard, CPU/cooler, memory, power supply, storage, display path, and basic input device are in scope.","quality":"exact"},"timing_change":{"response":"The system passed through an instructor checkpoint before the final symptom was observed; the exact change is not documented for the technician.","quality":"ambiguous"},"symptom_error":{"response":"The workstation does not currently reach the expected stable firmware screen with all assigned hardware detected.","quality":"exact"},"environment_equipment":{"response":"Use only the numbered parts kit, ESD mat, approved tools, known-good fallback items issued by the instructor, and bench monitor.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was performed after the symptom appeared.","quality":"exact"},"impact_urgency":{"response":"The workstation must pass hardware acceptance before it can be released to the Networking deployment step.","quality":"exact"}}'::jsonb),
  ('sc-hw-f26-final-d', 'PREPARATION: Number twelve complete caseless kits; verify compatibility and baseline; seal variant D. Students may use printed books and manufacturer resources.
EQUIPMENT: Motherboard, CPU/cooler, thermal interface material as required, RAM, PSU, storage, display/GPU path, keyboard, ESD mat, approved tools, POST reference, known-good fallback parts.
CAPACITY/ROTATION: Individual final in two waves of up to twelve. Wave B completes compatibility research, ticket analysis, component explanation preparation, and reset-plan review at desks while Wave A builds; then swap. No partner may touch or diagnose another student''s system.
ROLES: Each student is the sole technician for their numbered kit; the instructor is the client, safety authority, checkpoint verifier, and issuer of known-good fallback parts.
SETUP: Student builds from loose parts and reaches instructor checkpoint. With power removed and student away, instructor stages variant D: storage power disconnected after the initial build checkpoint.
DIAGNOSTIC BRANCHES: Power/no power; POST/memory; successful POST/no display; firmware storage inventory. Student must state why each test discriminates.
VERIFY: Safe complete build, component-function explanation, three cold starts, stable firmware CPU/RAM/storage detection, display/input response, root-cause evidence, readiness for FOG/Linux deployment or known-good laptop fallback.
RESET: De-energize/discharge, disassemble to labeled kit, clean thermal material only as directed, cap/store CPU and board safely, inventory every part/tool, restore staged item, instructor kit sign-off.
SIGN-OFF: Individual build, explanation, diagnosis, manufacturer research, repeated verification, complete reset.
PRINTED SERVICE LOG: One individual log linked to ticket; compatibility evidence; build checkpoints; five diagnostic rows; manufacturer source; final firmware inventory; reset initials.
SCOPE BOUNDARY: Do not open a power supply, bypass safety controls, install an operating system, or change drivers.', '{"scope":{"response":"The assigned motherboard, CPU/cooler, memory, power supply, storage, display path, and basic input device are in scope.","quality":"exact"},"timing_change":{"response":"The system passed through an instructor checkpoint before the final symptom was observed; the exact change is not documented for the technician.","quality":"ambiguous"},"symptom_error":{"response":"The workstation does not currently reach the expected stable firmware screen with all assigned hardware detected.","quality":"exact"},"environment_equipment":{"response":"Use only the numbered parts kit, ESD mat, approved tools, known-good fallback items issued by the instructor, and bench monitor.","quality":"exact"},"prior_troubleshooting":{"response":"No troubleshooting was performed after the symptom appeared.","quality":"exact"},"impact_urgency":{"response":"The workstation must pass hardware acceptance before it can be released to the Networking deployment step.","quality":"exact"}}'::jsonb);

insert into private.builtin_scenario_secrets (scenario_id, instructor_notes, client_responses) values
  ('sc-hw-01', 'Physical task: Unbox the PC Parts kit and identify each major component category at a glance — PSU, motherboard, RAM, CPU + cooler, GPU, storage. This is recognition, not deep analysis (that''s Week 3). Cover lab orientation and ESD basics, and introduce the Field Journal as the ongoing documentation habit for the quarter. Field Journal: inventory table by category with quantities, one labeled photo/sketch per component type.', '{}'::jsonb),
  ('sc-hw-02', 'Physical task: Identify and label every port and connector type present on the motherboards, PSUs, and drives in the parts kit — SATA data/power, 24-pin ATX, CPU 4/8-pin, PCIe power, USB headers, front-panel headers, video outputs. Match each connector to its cable and its correct use — this is also a good moment to (gently) confirm or debunk Sam''s confident guess. Field Journal: connector reference sheet with photos/sketches and what each one powers or carries.', '{}'::jsonb),
  ('sc-hw-03', 'Physical task: Full motherboard analysis using the ASRock boards from inventory — identify CPU socket type, RAM slot count/channels, expansion slot types (PCIe x16/x1), chipset, form factor, rear I/O. Visually inspect every board for damage (bent pins, bulging capacitors, burn marks) before any of them go into Week 5''s build. Field Journal: labeled motherboard diagram calling out every major component.', '{}'::jsonb),
  ('sc-hw-04', 'Physical task: Access BIOS/UEFI on available bench-capable systems (this quarter''s own builds don''t exist until next week — use existing stock). Record all settings found, correct as needed, note anything that would block a clean OS install later. Field Journal: settings audit table per machine, changes made with rationale.', '{}'::jsonb),
  ('sc-hw-11', 'Bonus/enrichment — not part of the required 10-week sequence, doesn''t map to a textbook chapter. Assign as extra credit, an open-lab activity, or filler for early finishers. Physical task: flash Raspberry Pi OS to a microSD card, boot the Pi, configure headless access (SSH + a static or reserved IP) with no monitor attached. 44 units in stock — one per student is realistic. Stretch step: connect the included Crickit add-on board and confirm it''s detected. Field Journal: imaging steps, headless connection method used, one command run successfully over SSH to prove access.', '{}'::jsonb),
  ('sc-cy-01', 'Physical task: Security baseline audit on assigned workstation — OS patch level, Windows Defender status, open ports via netstat. Document current security posture and any misconfigurations found. Field Journal: security baseline checklist with pass/fail for each item.', '{}'::jsonb),
  ('sc-cy-02', 'Physical task: Use Nmap to scan the lab subnet. Document all discovered hosts, open ports, and services. Flag any unexpected findings. Field Journal: Nmap output table — host, IP, open ports, services. Note anything that warrants further investigation.', '{}'::jsonb),
  ('sc-cy-03', 'Physical task: Audit local password policy on lab machine (min length, complexity, lockout thresholds). Compare against NIST SP 800-63B recommendations. Apply recommended changes. Field Journal: before/after policy settings table, summary of NIST guidelines and rationale for each change.', '{}'::jsonb),
  ('sc-cy-04', 'Controlled lab exercise with Hak5 WiFi Pineapple — perform passive recon scan, identify probe requests from devices, document what an attacker could observe. Field Journal: what data was visible, what the defensive implications are, and what specific mitigations would address the risk.', '{}'::jsonb),
  ('sc-cy-05', 'Physical task: Run vulnerability scan (OpenVAS, Nessus, or equivalent) against designated lab target VM. Categorize findings by severity (Critical/High/Medium/Low). Field Journal: top 5 findings with CVE numbers, severity ratings, and specific remediation steps for each.', '{}'::jsonb),
  ('sc-cy-06', 'Instructor stages a simulated malware alert on a lab machine (unusual processes, outbound connections visible in netstat). Students isolate the machine, collect evidence (process list, netstat, event logs), and write an incident response ticket. Field Journal: IR checklist — contain, collect, analyze, report. Reference PICERL framework.', '{}'::jsonb),
  ('sc-cy-07', 'Controlled lab exercise with Hak5 USB Rubber Ducky — execute a benign payload on lab machine, document what the attack accomplished and how fast it executed. Field Journal: attack timeline (from plug-in to completion), what defenses would have stopped it (USB policy, endpoint protection), recommended policy changes.', '{}'::jsonb),
  ('sc-cy-08', 'Physical task: Review Windows Firewall rules on lab machine. Identify overly permissive or unnecessary rules. Apply a default-deny outbound rule for a designated test application. Field Journal: before/after firewall rule table with justification for each change made.', '{}'::jsonb),
  ('sc-cy-09', 'Red vs Blue exercise: half class is red team (offensive), half is blue team managing the incident queue. Red team uses tools covered this quarter with instructor-defined scope. Blue team detects, documents, contains, reports. Field Journal: after-action report — what attacks succeeded, what was detected, what was missed, recommendations.', '{}'::jsonb),
  ('sc-cy-10', 'Capstone: Teams harden the complete lab environment built across all three courses. OS hardening, network segmentation, access controls, monitoring. Every change documented as a ticket. Field Journal: complete hardening checklist with evidence for each control, lessons learned across all three courses, final security posture statement.', '{}'::jsonb)
on conflict (scenario_id) do update set instructor_notes=excluded.instructor_notes;

create or replace function public.get_builtin_scenario_instructor_notes()
returns table (scenario_id text, instructor_notes text)
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not (select private.is_admin()) then
    raise exception 'admin_required' using errcode='42501';
  end if;
  return query
    select secret.scenario_id, secret.instructor_notes
    from private.builtin_scenario_secrets secret
    order by secret.scenario_id;
end;
$$;
revoke all on function public.get_builtin_scenario_instructor_notes() from public, anon, authenticated;
grant execute on function public.get_builtin_scenario_instructor_notes() to authenticated;

create or replace function public.create_lab_assignment_with_tickets(p_class_id uuid,p_week_label text,p_tickets jsonb)
returns uuid language plpgsql security definer set search_path = '' as $$
declare v_assignment_id uuid; v_ticket jsonb; v_ticket_id uuid; v_limit integer; v_responses jsonb; v_incident_id uuid;
begin
  if not (select private.is_admin()) then raise exception 'admin_required' using errcode='42501'; end if;
  if jsonb_typeof(p_tickets)<>'array' or jsonb_array_length(p_tickets)=0 then raise exception 'tickets_required'; end if;
  insert into public.lab_assignments(class_id,week_label,assigned_by) values(p_class_id,btrim(p_week_label),auth.uid()) returning id into v_assignment_id;
  for v_ticket in select value from jsonb_array_elements(p_tickets) item(value) loop
    v_limit:=coalesce((v_ticket->>'inquiry_limit')::integer,0);
    select secret.client_responses into v_responses
    from private.builtin_scenario_secrets secret
    where secret.scenario_id=v_ticket->>'scenario_id';
    if not found then v_responses:=coalesce(v_ticket->'client_responses','{}'::jsonb); end if;
    v_incident_id:=null;
    if v_limit not between 0 and 3 then raise exception 'invalid_inquiry_limit'; end if;
    if not private.valid_client_responses(v_limit,v_responses) then raise exception 'incomplete_client_responses'; end if;
    if nullif(v_ticket->>'team_key','') is not null then
      insert into public.team_incidents(assignment_id,team_key,team_name,color_name,color_hex,title,description)
      values(v_assignment_id,v_ticket->>'team_key',v_ticket->>'team_name',v_ticket->>'color_name',v_ticket->>'color_hex',v_ticket->>'title',v_ticket->>'description')
      on conflict(assignment_id,team_key) do update set
        team_name=excluded.team_name,color_name=excluded.color_name,color_hex=excluded.color_hex,
        title=excluded.title,description=excluded.description
      returning id into v_incident_id;
    end if;
    insert into public.assigned_tickets(assignment_id,student_id,group_tag,scenario_id,course_id,week,title,description,priority,status,inquiry_limit,team_incident_id)
    values(v_assignment_id,(v_ticket->>'student_id')::uuid,nullif(v_ticket->>'group_tag',''),v_ticket->>'scenario_id',v_ticket->>'course_id',(v_ticket->>'week')::integer,v_ticket->>'title',v_ticket->>'description',v_ticket->>'priority','New',v_limit,v_incident_id)
    returning id into v_ticket_id;
    if v_limit>0 then insert into private.assigned_ticket_scripts values(v_ticket_id,v_responses); end if;
    if v_incident_id is not null and nullif(v_ticket->>'team_role','') is not null then
      insert into public.team_contributions(assigned_ticket_id,student_id,team_role,contribution)
      values(v_ticket_id,(v_ticket->>'student_id')::uuid,v_ticket->>'team_role',null);
    end if;
  end loop; return v_assignment_id;
end; $$;
revoke all on function public.create_lab_assignment_with_tickets(uuid,text,jsonb) from public,anon,authenticated;
grant execute on function public.create_lab_assignment_with_tickets(uuid,text,jsonb) to authenticated;
