-- Shared, moderated knowledge base for Cinder.
-- Run this migration before deploying the matching application changes.

create schema if not exists private;

create or replace function private.is_kb_reviewer()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select (select auth.uid()) is not null
    and exists (
      select 1
      from public.profiles
      where id = (select auth.uid())
        and role in ('admin', 'tech')
    );
$$;

revoke all on function private.is_kb_reviewer() from public;
grant usage on schema private to authenticated;
grant execute on function private.is_kb_reviewer() to authenticated;

create table if not exists public.knowledge_articles (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null check (char_length(title) between 1 and 180),
  course_id text,
  category text not null default 'General',
  status text not null default 'draft'
    check (status in ('draft', 'submitted', 'changes_requested', 'published', 'archived')),
  author_id uuid not null references public.profiles(id) on delete restrict,
  reviewer_id uuid references public.profiles(id) on delete set null,
  body text not null default '',
  tags text[] not null default '{}',
  review_notes text,
  source_type text,
  source_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  submitted_at timestamptz,
  published_at timestamptz
);

create table if not exists public.knowledge_article_revisions (
  id bigint generated by default as identity primary key,
  article_id uuid not null references public.knowledge_articles(id) on delete cascade,
  editor_id uuid not null references public.profiles(id) on delete restrict,
  title text not null,
  body text not null,
  tags text[] not null default '{}',
  status text not null,
  change_summary text not null default 'Article updated',
  created_at timestamptz not null default now()
);

create index if not exists knowledge_articles_author_idx on public.knowledge_articles(author_id);
create index if not exists knowledge_articles_status_idx on public.knowledge_articles(status);
create index if not exists knowledge_articles_course_idx on public.knowledge_articles(course_id);
create index if not exists knowledge_article_revisions_article_idx on public.knowledge_article_revisions(article_id, created_at desc);

create or replace function public.set_knowledge_article_updated_at()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

revoke all on function public.set_knowledge_article_updated_at() from public;

drop trigger if exists set_knowledge_article_updated_at on public.knowledge_articles;
create trigger set_knowledge_article_updated_at
before update on public.knowledge_articles
for each row execute function public.set_knowledge_article_updated_at();

alter table public.knowledge_articles enable row level security;
alter table public.knowledge_article_revisions enable row level security;

revoke all on public.knowledge_articles from anon;
revoke all on public.knowledge_article_revisions from anon;
grant select, insert, update, delete on public.knowledge_articles to authenticated;
grant select, insert on public.knowledge_article_revisions to authenticated;
grant usage, select on sequence public.knowledge_article_revisions_id_seq to authenticated;

create policy "Read published articles, own drafts, or review queue"
on public.knowledge_articles for select
to authenticated
using (
  status = 'published'
  or author_id = (select auth.uid())
  or (select private.is_kb_reviewer())
);

create policy "Students create their own drafts and submissions"
on public.knowledge_articles for insert
to authenticated
with check (
  author_id = (select auth.uid())
  and status in ('draft', 'submitted')
  and reviewer_id is null
  and review_notes is null
  and published_at is null
);

create policy "Reviewers create articles"
on public.knowledge_articles for insert
to authenticated
with check ((select private.is_kb_reviewer()));

create policy "Students update their editable articles"
on public.knowledge_articles for update
to authenticated
using (
  author_id = (select auth.uid())
  and status in ('draft', 'changes_requested')
)
with check (
  author_id = (select auth.uid())
  and status in ('draft', 'submitted')
  and reviewer_id is null
  and published_at is null
);

create policy "Reviewers update all articles"
on public.knowledge_articles for update
to authenticated
using ((select private.is_kb_reviewer()))
with check ((select private.is_kb_reviewer()));

create policy "Students delete their own drafts"
on public.knowledge_articles for delete
to authenticated
using (author_id = (select auth.uid()) and status = 'draft');

create policy "Reviewers delete articles"
on public.knowledge_articles for delete
to authenticated
using ((select private.is_kb_reviewer()));

create policy "Authors and reviewers read revision history"
on public.knowledge_article_revisions for select
to authenticated
using (
  editor_id = (select auth.uid())
  or exists (
    select 1 from public.knowledge_articles article
    where article.id = article_id
      and article.author_id = (select auth.uid())
  )
  or (select private.is_kb_reviewer())
);

create policy "Authors and reviewers add revisions"
on public.knowledge_article_revisions for insert
to authenticated
with check (
  editor_id = (select auth.uid())
  and (
    exists (
      select 1 from public.knowledge_articles article
      where article.id = article_id
        and article.author_id = (select auth.uid())
    )
    or (select private.is_kb_reviewer())
  )
);
